Fix for servers with a lot of long emoji names
This caused the following exception on one of my servers:
System.ArgumentException: Field value length must be less than or
equal to 1024.